CREATE TABLE [staging].[IdentityCA] (
    [LineageRowID]           BIGINT         NOT NULL,
    [BusinessID]             INT            NULL,
    [DunsNumber]             VARCHAR (10)   NOT NULL,
    [DataFeedEffectiveDate]  INT            NOT NULL,
    [BusinessName]           NVARCHAR (500) NULL,
    [AddressLine]            NVARCHAR (500) NULL,
    [City]                   NVARCHAR (255) NULL,
    [State]                  NVARCHAR (255) NULL,
    [ZipCode]                NVARCHAR (255) NULL,
    [Country]                NVARCHAR (100) NULL,
    [Telephone]              NVARCHAR (100) NULL,
    [LocationType]           NVARCHAR (2)   NULL,
    [OutofBusinessIndicator] NVARCHAR (2)   NULL,
    [PrimarySIC]             NVARCHAR (255) NULL,
    [StopDistributionInd]    NVARCHAR (2)   NULL,
    [TradeStyle1]            NVARCHAR (250) NULL,
    [TradeStyle2]            NVARCHAR (250) NULL,
    [TradeStyle3]            NVARCHAR (250) NULL,
    [TradeStyle4]            NVARCHAR (250) NULL,
    [TradeStyle5]            NVARCHAR (250) NULL,
    [CEOName]                NVARCHAR (255) NULL,
    [LegalStructure]         NVARCHAR (10)  NULL,
    [PublicPrivateIndicator] NVARCHAR (10)  NULL,
    [MovedIndicator]         NVARCHAR (50)  NULL,
    [GeoRefId]               NVARCHAR (50)  NULL,
    [ExecutionID]            INT            NOT NULL
) ON [STAGING];

