CREATE TABLE [staging].[SubjectAcxiom] (
    [LineageRowID]                         BIGINT          NOT NULL,
    [BusinessID]                           BIGINT          NULL,
    [DunsNumber]                           VARCHAR (9)     NOT NULL,
    [DataFeedEffectiveDate]                INT             NOT NULL,
    [StopDistributionIndicator]            NVARCHAR (1)    NULL,
    [DeletionIndicator]                    NVARCHAR (1)    NULL,
    [TransferReasonCode]                   NVARCHAR (6)    NULL,
    [CountryCode]                          NVARCHAR (6)    NULL,
    [InfoSourceCode]                       NVARCHAR (6)    NULL,
    [RecordTypeCode]                       NVARCHAR (6)    NULL,
    [BusinessName]                         NVARCHAR (240)  NULL,
    [TradeStyles1]                         NVARCHAR (240)  NULL,
    [TradeStyles2]                         NVARCHAR (240)  NULL,
    [TradeStyles3]                         NVARCHAR (240)  NULL,
    [PrimaryAddressLine1]                  NVARCHAR (120)  NULL,
    [PrimaryAddressLine2]                  NVARCHAR (120)  NULL,
    [PrimaryAddressLine3]                  NVARCHAR (120)  NULL,
    [PrimaryAddressLine4]                  NVARCHAR (120)  NULL,
    [PrimaryTown]                          NVARCHAR (64)   NULL,
    [PrimaryCounty]                        NVARCHAR (64)   NULL,
    [PrimaryPostalCd]                      NVARCHAR (16)   NULL,
    [RegisteredAddressLine1]               NVARCHAR (120)  NULL,
    [RegisteredAddressLine2]               NVARCHAR (120)  NULL,
    [RegisteredAddressLine3]               NVARCHAR (120)  NULL,
    [RegisteredAddressLine4]               NVARCHAR (120)  NULL,
    [RegisteredTown]                       NVARCHAR (64)   NULL,
    [RegisteredCounty]                     NVARCHAR (64)   NULL,
    [RegisteredPostalCd]                   NVARCHAR (16)   NULL,
    [PrimarySICType]                       NVARCHAR (6)    NULL,
    [PrimarySIC]                           NVARCHAR (16)   NULL,
    [LocalActivityCodeType]                NVARCHAR (6)    NULL,
    [LocalActivityCode]                    NVARCHAR (16)   NULL,
    [TelephoneNumber]                      NVARCHAR (14)   NULL,
    [RegistrationNumberPrefix]             NVARCHAR (16)   NULL,
    [RegistrationNumber]                   NVARCHAR (32)   NULL,
    [RegistrationNumberSuffix]             NVARCHAR (16)   NULL,
    [VatNumberPrefix]                      NVARCHAR (16)   NULL,
    [VatNumber]                            NVARCHAR (32)   NULL,
    [VatNumberSuffix]                      NVARCHAR (16)   NULL,
    [StartYear]                            INT             NULL,
    [OutOfBusinessIndicator]               NVARCHAR (20)   NULL,
    [IssuedCapital]                        DECIMAL (19, 4) NULL,
    [IssuedCapitalCurrencyCode]            NVARCHAR (6)    NULL,
    [IncorporationYear]                    INT             NULL,
    [LegalStructure]                       NVARCHAR (6)    NULL,
    [DnBRatingFinancialStrength]           NVARCHAR (6)    NULL,
    [DnBRatingRiskIndicator]               NVARCHAR (6)    NULL,
    [MaximumCreditRecommendation]          DECIMAL (19, 4) NULL,
    [CurrencyCode1]                        NVARCHAR (6)    NULL,
    [SevereNegativeInformation]            NVARCHAR (6)    NULL,
    [DnBFailureScore]                      SMALLINT        NULL,
    [DnBDelinquencyScore]                  SMALLINT        NULL,
    [DnBFailureScore1months]               SMALLINT        NULL,
    [DnBFailureScore2months]               SMALLINT        NULL,
    [DnBFailureScore3months]               SMALLINT        NULL,
    [DnBFailureScore4months]               SMALLINT        NULL,
    [DnBFailureScore5months]               SMALLINT        NULL,
    [DnBFailureScore6months]               SMALLINT        NULL,
    [DnBFailureScore7months]               SMALLINT        NULL,
    [DnBFailureScore8months]               SMALLINT        NULL,
    [DnBFailureScore9months]               SMALLINT        NULL,
    [DnBFailureScore10months]              SMALLINT        NULL,
    [DnBFailureScore11months]              SMALLINT        NULL,
    [DnBFailureScore12months]              SMALLINT        NULL,
    [LegalEvent1YearTotalAmount]           DECIMAL (19, 4) NULL,
    [LegalEvent1YearTotalAmountCurrencyCd] NVARCHAR (6)    NULL,
    [DnBPaydex]                            SMALLINT        NULL,
    [StatementDate]                        NVARCHAR (20)   NULL,
    [TangibleNetWorth]                     DECIMAL (19, 4) NULL,
    [TotalEmployees]                       BIGINT          NULL,
    [CurrencyCode2]                        NVARCHAR (6)    NULL,
    [Sales]                                DECIMAL (19, 4) NULL,
    [CostofSales]                          DECIMAL (19, 4) NULL,
    [ProfitBeforeTax]                      DECIMAL (19, 4) NULL,
    [NetProfit]                            DECIMAL (19, 4) NULL,
    [NetLoss]                              DECIMAL (19, 4) NULL,
    [FixedAssets]                          DECIMAL (19, 4) NULL,
    [TotalCurrentAssets]                   DECIMAL (19, 4) NULL,
    [TotalAssets]                          DECIMAL (19, 4) NULL,
    [IntangibleAssets]                     DECIMAL (19, 4) NULL,
    [TotalCurrentLiabilities]              DECIMAL (19, 4) NULL,
    [TotalLiabilities]                     DECIMAL (19, 4) NULL,
    [TotalLongTermLiabilities]             DECIMAL (19, 4) NULL,
    [CurrentRatio]                         DECIMAL (19, 4) NULL,
    [PreviousStatementDate]                NVARCHAR (20)   NULL,
    [PreviousNetWorth]                     DECIMAL (19, 4) NULL,
    [CurrencyCode3]                        NVARCHAR (6)    NULL,
    [PreviousCurrentAssets]                DECIMAL (19, 4) NULL,
    [TotalAssetsYear2]                     DECIMAL (19, 4) NULL,
    [PreviousCurrentLiaiblities]           DECIMAL (19, 4) NULL,
    [TotalLiabilitiesYear2]                DECIMAL (19, 4) NULL,
    [DomesticUltimateName]                 NVARCHAR (90)   NULL,
    [DomesticUltimateCountryCode]          NVARCHAR (3)    NULL,
    [ParentCountry]                        NVARCHAR (6)    NULL,
    [DomesticUltimateDunsNumber]           VARCHAR (9)     NULL,
    [GlobalUltimateDnBDunsNumber]          VARCHAR (9)     NULL,
    [HeadquartersDnBDunsNumber]            VARCHAR (9)     NULL,
    [GlobalUltimateCountry]                NVARCHAR (3)    NULL,
    [GlobalUltimateName]                   NVARCHAR (90)   NULL,
    [ParentDunsNumber]                     VARCHAR (9)     NULL,
    [HeadquartersName]                     NVARCHAR (240)  NULL,
    [ParentName]                           NVARCHAR (240)  NULL,
    [HeadquartersCountryCode]              NVARCHAR (3)    NULL,
    [HeadquarterStreetAddress]             NVARCHAR (64)   NULL,
    [HeadquarterCity]                      NVARCHAR (30)   NULL,
    [HeadquarterState]                     NVARCHAR (30)   NULL,
    [HeadquarterCountryName]               NVARCHAR (20)   NULL,
    [HeadquarterCityCode]                  NVARCHAR (6)    NULL,
    [HeadquarterCountyCode]                NVARCHAR (3)    NULL,
    [HeadquarterProvinceAbbreviation]      NVARCHAR (4)    NULL,
    [HeadquarterPostalCode]                NVARCHAR (9)    NULL,
    [HeadquarterContinentCode]             NVARCHAR (1)    NULL,
    [NarrationCode]                        NVARCHAR (255)  NULL,
    [EmployeeQuantity]                     NVARCHAR (255)  NULL,
    [LegalFormtext]                        NVARCHAR (255)  NULL,
    [LegalEvent1YearTotalCount]            BIGINT          NULL,
    [LegalEvent5YearTotalCount]            BIGINT          NULL,
    [LegalEvent5YearTotalAmount]           DECIMAL (19, 4) NULL,
    [LegalEvent5YearTotalAmountCurrencyCd] NVARCHAR (20)   NULL,
    [ExecutionID]                          INT             NOT NULL,
    [GlobalCompanyProfile]                 BIT             NOT NULL,
    [Identity]                             BIT             NOT NULL,
    [CcsFss]                               BIT             NOT NULL,
    [Paydex]                               BIT             NOT NULL,
    [Subject]                              BIT             NOT NULL,
    [Financial]                            BIT             NOT NULL
) ON [STAGING];





