CREATE TABLE [feed].[Financial] (
    [BusinessID]                            INT           NOT NULL,
    [DunsNumber]                            NVARCHAR (9)  NOT NULL,
    [DataSource]                            NVARCHAR (64) NOT NULL,
    [StatementDate]                         DATE          NOT NULL,
    [StatementType]                         NVARCHAR (64) NOT NULL,
    [StatementTypeCode]                     CHAR (1)      NULL,
    [IsPublicCompany]                       BIT           NULL,
    [CashAndCashEquivalents]                MONEY         NULL,
    [AccountsReceivables]                   MONEY         NULL,
    [TotalCurrentAssets]                    MONEY         NULL,
    [NetTangibleAssets]                     MONEY         NULL,
    [Inventory]                             MONEY         NULL,
    [NetFixedAssets]                        MONEY         NULL,
    [TotalAssets]                           MONEY         NULL,
    [AccountsPayable]                       MONEY         NULL,
    [TotalCurrentLiabilities]               MONEY         NULL,
    [TotalLiabilities]                      MONEY         NULL,
    [NetWorth]                              MONEY         NULL,
    [IntangibleAssets]                      MONEY         NULL,
    [BankDebt]                              MONEY         NULL,
    [IssuedCapital]                         MONEY         NULL,
    [IssuedCapitalCurrencyCode]             VARCHAR (10)  NULL,
    [TangibleNetWorth]                      MONEY         NULL,
    [GoodWill]                              MONEY         NULL,
    [CurrencyCode]                          VARCHAR (10)  NULL,
    [SalesRevenue]                          MONEY         NULL,
    [GrossProfit]                           MONEY         NULL,
    [EarningsBeforeInterestAndTaxes]        MONEY         NULL,
    [InterestExpense]                       MONEY         NULL,
    [EarningBeforeTax]                      MONEY         NULL,
    [OperatingIncome]                       MONEY         NULL,
    [NetIncome]                             MONEY         NULL,
    [CostOfSales]                           MONEY         NULL,
    [NetLoss]                               MONEY         NULL,
    [NetProfit]                             MONEY         NULL,
    [TotalOtherIncomeAndExpensesNet]        MONEY         NULL,
    [ResearchAndDevelopment]                MONEY         NULL,
    [SellingGeneralAndAd]                   MONEY         NULL,
    [NonRecurring]                          MONEY         NULL,
    [OtherOperatingExpenses]                MONEY         NULL,
    [NetDepreciationAndAmortizationExpense] MONEY         NULL,
    [CashFlowFromFinancingActivities]       MONEY         NULL,
    [CashFlowFromInvestingActivities]       MONEY         NULL,
    [ChangeInCashAndCashEquivalents]        MONEY         NULL,
    [CashFlowFromOperatingActivities]       MONEY         NULL,
    [CapitalExpenditure]                    MONEY         NULL,
    [TotalSharesOutstanding]                MONEY         NULL,
    [AnnualSales]                           MONEY         NULL,
	[LineageRowID]                          INT           NOT NULL,
    [DataFeedEffectiveDate]                 INT           NOT NULL,
    [CreatedDate]                           DATETIME      CONSTRAINT [DF_Financial_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]                             VARCHAR (50)  NOT NULL,
    [UpdatedDate]                           DATETIME      NULL,
    [UpdatedBy]                             VARCHAR (50)  NULL,
    CONSTRAINT [PK_Financial] PRIMARY KEY CLUSTERED ([DunsNumber] ASC, [DataSource] ASC, [StatementDate] ASC, [StatementType] ASC) ON [FEED]
)







