CREATE TABLE [feed].[GlobalCompanyProfile] (
    [BusinessID]                     INT             NOT NULL,
    [DunsNumber]                     VARCHAR (10)    NULL,
    [Address3]                       NVARCHAR (100)  NULL,
    [Address4]                       NVARCHAR (100)  NULL,
    [RegistrationNumber]             NVARCHAR (32)   NULL,
    [VATNumber]                      VARCHAR (50)    NULL,
    [SeverNegativeInfo]              VARCHAR (50)    NULL,
    [RegAddressLine1]                NVARCHAR (100)  NULL,
    [RegAddressLine2]                NVARCHAR (100)  NULL,
    [RegAddressLine3]                NVARCHAR (100)  NULL,
    [RegAddressLine4]                NVARCHAR (100)  NULL,
    [RegState]                       VARCHAR (50)    NULL,
    [RegPostalCode]                  VARCHAR (50)    NULL,
    [RegCity]                        VARCHAR (50)    NULL,
    [LocalActivityCode]              VARCHAR (50)    NULL,
    [LocalActivityType]              VARCHAR (50)    NULL,
    [DNBRatingFinancialStrength]     VARCHAR (50)    NULL,
    [DNBRatingRiskInd]               VARCHAR (50)    NULL,
    [ScorePeriodDate]                VARCHAR (50)    NULL,
    [MaxCreditRec]                   VARCHAR (50)    NULL,
    [CurrencyCode]                   VARCHAR (50)    NULL,
    [RecCreditOverrideCond]          VARCHAR (50)    NULL,
    [LegalEventAmtYr1]               DECIMAL (19, 4) NULL,
    [LegalEvent1YrCurrCD]            NVARCHAR (6)    NULL,
    [LegalEventCnt1yr]               INT             NULL,
    [LegalEventAmtYr5]               DECIMAL (19, 4) NULL,
    [LegalEvent5YrCurrCD]            NVARCHAR (6)    NULL,
    [LegalEventCntYr5]               INT             NULL,
    [LegalFormText]                  NVARCHAR(500)    NULL,
    [IssuedCapital]                  DECIMAL (19, 4) NULL,
    [IssuedCapitalCurrencyCode]      NVARCHAR (6)    NULL,
    [IssuedCapitalCurrencyCodeValue] VARCHAR (3)     NULL,
    [RecordTypeCode]                 NVARCHAR (6)    NULL,
    [RecordTypeCodeValue]            NVARCHAR (256)  NULL,
    [TransferReasonCode]             NVARCHAR (6)    NULL,
    [TransferReasonCodeValue]        NVARCHAR (256)  NULL,
    [InfoSourceCode]                 NVARCHAR (6)    NULL,
    [InfoSourceCodeValue]            NVARCHAR (256)  NULL,
    [DeletionIndicator]              BIT             NULL,
    [StopDistributionIndicator]      BIT             NULL,
    [CreatedDate]                    DATETIME        CONSTRAINT [DF_GlobalCompanyProfile_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]                      VARCHAR (50)    NOT NULL,
    [UpdatedDate]                    DATETIME        NULL,
    [UpdatedBy]                      VARCHAR (50)    NULL,
    CONSTRAINT [PK_GlobalCompanyProfile] PRIMARY KEY CLUSTERED ([BusinessID] ASC) ON [FEED]
);



